/* 2026 by Piotr Rozentreter (Rozsoft) */

#ifndef PY68K_CONFIG_DEFAULT_H
#define PY68K_CONFIG_DEFAULT_H

#define PY68K_LANGUAGE_LEVEL 1
#define PY68K_VERSION_MAJOR 0
#define PY68K_VERSION_MINOR 1
#define PY68K_VERSION_PATCH 0

#endif
